In [9]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[1,3,5], [2,6,8]])
arr > arr2


array([[False, False, False],
       [ True, False, False]])

In [10]:
arr = np.arange(10)
print(arr)
# slice array
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[:] = 12
print(arr_slice)
print(arr)

# array slicing without copying
print("New arr")
newarr =  np.arange(10)
newarr_slice = newarr[5:8].copy()
print(newarr_slice)
newarr_slice[:] = 12
print(newarr_slice)
print(newarr)



[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[12 12 12]
[ 0  1  2  3  4 12 12 12  8  9]
New arr
[5 6 7]
[12 12 12]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
# working with 2 ndarrays
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[0][2])

3


In [12]:
# creating 3 ndarrays
arr3d= np.array([[[1,2,3], [1,2,3]], [[4,5,6], [7,8,9]]])
arr3d
newarr = arr3d[0]
newnewarr = newarr[0]
print(newnewarr[0])

1


In [25]:
# testing arrays with names
names = np.array(['zion', 'daisy', 'williams', 'linda'])
data = np.random.randn(4, 4)



In [29]:
names == 'zion'
print(data)
data[names=='zion'] = 7
data[names == 'zion']


[[ 7.          7.          7.          7.        ]
 [ 1.54277964  0.94760819  0.48401762  1.13221959]
 [ 0.13617118  0.24794335 -1.00965859 -0.1823322 ]
 [-0.54907946  1.47966795 -1.11225585 -0.9877515 ]]


array([[7., 7., 7., 7.]])

In [30]:
# working on fancy indexing
arr = np.empty((8, 4))
arr

array([[5.08859412e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [6.55378400e-310, 5.02034658e+175, 3.43631247e+179,
        3.77025433e-061],
       [9.33348171e+164, 2.22935390e+180, 8.23825551e-043,
        6.47073340e-144],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        2.59027926e-144],
       [3.80985069e+180, 5.13112925e+199, 9.29610348e+199,
        1.35617292e+248],
       [5.12944426e-072, 5.59151431e-091, 8.61691948e-043,
        2.34394419e-056],
       [1.10507077e-046, 5.28555805e+180, 2.89755778e-057,
        6.97936820e-076],
       [4.66499551e-086, 3.35609385e-143, 9.30350598e+199,
        4.24941018e-086]])